#define ID_SIZE 40
#define TITLE_SIZE 64
#define ARTIST_SIZE 256
#define NAME_SIZE 256
#define RESOURCE_SIZE 128
#define URL_SIZE 128
#define SERVICE_TYPE_SIZE 128

#define ARDUINO_STACK 8192
#define ARDUINO_PRIORITY 1
#define ARDUINO_CORE 1

#define WIFI_CONNECTED_BIT 0x01
#define STOP_BIT 0x02

#define WAIT_ALL pdTRUE
#define WAIT_ONE pdFALSE
#define CLEAR_ON_EXIT pdTRUE
#define NO_CLEAR pdFALSE
